{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "Using TensorFlow backend.\n",
      "Setting start episode to 0\n",
      "2018-06-17 03:39:06.193147: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:10.500589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 11.63GiB\n",
      "2018-06-17 03:39:10.500685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "Loading model: go_3res_block_15/MCTS/model_0.hdf5\n",
      "__________________________________________________________________________________________________\n",
      "Layer (type)                    Output Shape         Param #     Connected to                     \n",
      "==================================================================================================\n",
      "input_1 (InputLayer)            (None, 11, 11, 18)   0                                            \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_1 (Conv2D)               (None, 11, 11, 256)  41728       input_1[0][0]                    \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_1 (BatchNor (None, 11, 11, 256)  1024        conv2d_1[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "activation_1 (Activation)       (None, 11, 11, 256)  0           batch_normalization_1[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_2 (Conv2D)               (None, 11, 11, 256)  590080      activation_1[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_2 (BatchNor (None, 11, 11, 256)  1024        conv2d_2[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "activation_2 (Activation)       (None, 11, 11, 256)  0           batch_normalization_2[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_3 (Conv2D)               (None, 11, 11, 256)  590080      activation_2[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_3 (BatchNor (None, 11, 11, 256)  1024        conv2d_3[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "add_1 (Add)                     (None, 11, 11, 256)  0           activation_1[0][0]               \n",
      "                                                                 batch_normalization_3[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "activation_3 (Activation)       (None, 11, 11, 256)  0           add_1[0][0]                      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_4 (Conv2D)               (None, 11, 11, 256)  590080      activation_3[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_4 (BatchNor (None, 11, 11, 256)  1024        conv2d_4[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "activation_4 (Activation)       (None, 11, 11, 256)  0           batch_normalization_4[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_5 (Conv2D)               (None, 11, 11, 256)  590080      activation_4[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_5 (BatchNor (None, 11, 11, 256)  1024        conv2d_5[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "add_2 (Add)                     (None, 11, 11, 256)  0           activation_3[0][0]               \n",
      "                                                                 batch_normalization_5[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "activation_5 (Activation)       (None, 11, 11, 256)  0           add_2[0][0]                      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_6 (Conv2D)               (None, 11, 11, 256)  590080      activation_5[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_6 (BatchNor (None, 11, 11, 256)  1024        conv2d_6[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "activation_6 (Activation)       (None, 11, 11, 256)  0           batch_normalization_6[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_7 (Conv2D)               (None, 11, 11, 256)  590080      activation_6[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_7 (BatchNor (None, 11, 11, 256)  1024        conv2d_7[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "add_3 (Add)                     (None, 11, 11, 256)  0           activation_5[0][0]               \n",
      "                                                                 batch_normalization_7[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "activation_7 (Activation)       (None, 11, 11, 256)  0           add_3[0][0]                      \n",
      "__________________________________________________________________________________________________\n",
      "conv2d_8 (Conv2D)               (None, 11, 11, 2)    514         activation_7[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "batch_normalization_8 (BatchNor (None, 11, 11, 2)    8           conv2d_8[0][0]                   \n",
      "__________________________________________________________________________________________________\n",
      "activation_8 (Activation)       (None, 11, 11, 2)    0           batch_normalization_8[0][0]      \n",
      "__________________________________________________________________________________________________\n",
      "flatten_1 (Flatten)             (None, 242)          0           activation_8[0][0]               \n",
      "__________________________________________________________________________________________________\n",
      "actions (Dense)                 (None, 6)            1458        flatten_1[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "reward (Dense)                  (None, 1)            243         flatten_1[0][0]                  \n",
      "==================================================================================================\n",
      "Total params: 3,591,599\n",
      "Trainable params: 3,588,011\n",
      "Non-trainable params: 3,588\n",
      "__________________________________________________________________________________________________\n",
      "Starting training in main process\n",
      "################### ITERATION 1 ###################\n",
      "Generate dataset\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating child processes\n",
      "Setting start episode to 0\n",
      "  0%|                                                   | 0/150 [00:00<?, ?it/s]Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2018-06-17 03:39:31.773095: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.773097: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.773097: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.773125: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.773906: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.773958: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.774078: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.774130: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.774131: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.774151: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.774186: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:31.774189: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 03:39:40.553238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 10.77GiB\n",
      "2018-06-17 03:39:40.553341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "2018-06-17 03:39:40.563131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 10.30GiB\n",
      "2018-06-17 03:39:40.563237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.565628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 10.30GiB\n",
      "2018-06-17 03:39:40.565744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "2018-06-17 03:39:40.581422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 9.37GiB\n",
      "2018-06-17 03:39:40.581472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.586008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 9.14GiB\n",
      "2018-06-17 03:39:40.586088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.588034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 9.14GiB\n",
      "2018-06-17 03:39:40.588112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.588175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 9.14GiB\n",
      "2018-06-17 03:39:40.588239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "2018-06-17 03:39:40.591644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 8.44GiB\n",
      "2018-06-17 03:39:40.591702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "2018-06-17 03:39:40.597102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 8.21GiB\n",
      "2018-06-17 03:39:40.597152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.597227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 8.21GiB\n",
      "2018-06-17 03:39:40.597280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.597310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 8.21GiB\n",
      "2018-06-17 03:39:40.597364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "2018-06-17 03:39:40.597375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: \n",
      "name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n",
      "pciBusID: 0000:05:00.0\n",
      "totalMemory: 11.91GiB freeMemory: 8.21GiB\n",
      "2018-06-17 03:39:40.597432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:05:00.0, compute capability: 6.0)\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "\u001b[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.\u001b[0m\n",
      "100%|██████████████████████████████████████| 150/150 [4:56:31<00:00, 118.61s/it]\n",
      "Finishing\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "RUNNER KILLED\n",
      "All childs was killed\n",
      "Train on 41515 samples, validate on 7327 samples\n",
      "Epoch 1/150\n",
      "41515/41515 [==============================] - 17s 407us/step - loss: 0.6887 - actions_loss: 0.4492 - reward_loss: 0.2395 - actions_acc: 0.8753 - reward_acc: 0.8937 - val_loss: 0.7672 - val_actions_loss: 0.6278 - val_reward_loss: 0.1394 - val_actions_acc: 0.7674 - val_reward_acc: 0.9326\n",
      "Epoch 2/150\n",
      "41515/41515 [==============================] - 13s 324us/step - loss: 0.3869 - actions_loss: 0.2086 - reward_loss: 0.1783 - actions_acc: 0.9348 - reward_acc: 0.9170 - val_loss: 0.7163 - val_actions_loss: 0.5221 - val_reward_loss: 0.1943 - val_actions_acc: 0.8359 - val_reward_acc: 0.9154\n",
      "Epoch 3/150\n",
      "41515/41515 [==============================] - 13s 324us/step - loss: 0.2687 - actions_loss: 0.1172 - reward_loss: 0.1516 - actions_acc: 0.9660 - reward_acc: 0.9265 - val_loss: 0.6986 - val_actions_loss: 0.4978 - val_reward_loss: 0.2009 - val_actions_acc: 0.8794 - val_reward_acc: 0.8839\n",
      "Epoch 4/150\n",
      "41515/41515 [==============================] - 13s 322us/step - loss: 0.2128 - actions_loss: 0.0786 - reward_loss: 0.1342 - actions_acc: 0.9766 - reward_acc: 0.9351 - val_loss: 0.7728 - val_actions_loss: 0.5204 - val_reward_loss: 0.2524 - val_actions_acc: 0.8656 - val_reward_acc: 0.8553\n",
      "Epoch 5/150\n",
      "41515/41515 [==============================] - 13s 322us/step - loss: 0.1810 - actions_loss: 0.0641 - reward_loss: 0.1170 - actions_acc: 0.9813 - reward_acc: 0.9410 - val_loss: 0.7847 - val_actions_loss: 0.5283 - val_reward_loss: 0.2564 - val_actions_acc: 0.8420 - val_reward_acc: 0.8459\n",
      "Epoch 6/150\n",
      "41515/41515 [==============================] - 13s 324us/step - loss: 0.1366 - actions_loss: 0.0593 - reward_loss: 0.0773 - actions_acc: 0.9816 - reward_acc: 0.9646 - val_loss: 0.8425 - val_actions_loss: 0.5289 - val_reward_loss: 0.3136 - val_actions_acc: 0.8732 - val_reward_acc: 0.8289\n",
      "Epoch 7/150\n",
      "41515/41515 [==============================] - 13s 322us/step - loss: 0.1082 - actions_loss: 0.0580 - reward_loss: 0.0502 - actions_acc: 0.9824 - reward_acc: 0.9787 - val_loss: 0.8327 - val_actions_loss: 0.5490 - val_reward_loss: 0.2838 - val_actions_acc: 0.8540 - val_reward_acc: 0.8253\n",
      "Epoch 8/150\n",
      "41515/41515 [==============================] - 13s 324us/step - loss: 0.0956 - actions_loss: 0.0539 - reward_loss: 0.0417 - actions_acc: 0.9841 - reward_acc: 0.9846 - val_loss: 0.8317 - val_actions_loss: 0.5273 - val_reward_loss: 0.3044 - val_actions_acc: 0.8682 - val_reward_acc: 0.8242\n",
      "Epoch 9/150\n",
      "41515/41515 [==============================] - 14s 337us/step - loss: 0.0855 - actions_loss: 0.0504 - reward_loss: 0.0351 - actions_acc: 0.9841 - reward_acc: 0.9881 - val_loss: 0.8598 - val_actions_loss: 0.5468 - val_reward_loss: 0.3131 - val_actions_acc: 0.8677 - val_reward_acc: 0.8230\n",
      "Epoch 10/150\n",
      "41515/41515 [==============================] - 15s 360us/step - loss: 0.0789 - actions_loss: 0.0465 - reward_loss: 0.0323 - actions_acc: 0.9853 - reward_acc: 0.9894 - val_loss: 0.8731 - val_actions_loss: 0.5553 - val_reward_loss: 0.3178 - val_actions_acc: 0.8586 - val_reward_acc: 0.8317\n",
      "Epoch 11/150\n",
      "41515/41515 [==============================] - 17s 406us/step - loss: 0.0758 - actions_loss: 0.0465 - reward_loss: 0.0293 - actions_acc: 0.9855 - reward_acc: 0.9904 - val_loss: 0.8616 - val_actions_loss: 0.5695 - val_reward_loss: 0.2921 - val_actions_acc: 0.8698 - val_reward_acc: 0.8257\n",
      "Epoch 12/150\n",
      "41515/41515 [==============================] - 17s 408us/step - loss: 0.0709 - actions_loss: 0.0422 - reward_loss: 0.0287 - actions_acc: 0.9857 - reward_acc: 0.9911 - val_loss: 0.8611 - val_actions_loss: 0.5588 - val_reward_loss: 0.3023 - val_actions_acc: 0.8735 - val_reward_acc: 0.8272\n",
      "Epoch 13/150\n",
      "41515/41515 [==============================] - 17s 421us/step - loss: 0.0708 - actions_loss: 0.0415 - reward_loss: 0.0292 - actions_acc: 0.9863 - reward_acc: 0.9915 - val_loss: 0.8760 - val_actions_loss: 0.5825 - val_reward_loss: 0.2935 - val_actions_acc: 0.8736 - val_reward_acc: 0.8279\n",
      "Epoch 14/150\n",
      "41515/41515 [==============================] - 17s 407us/step - loss: 0.0564 - actions_loss: 0.0344 - reward_loss: 0.0220 - actions_acc: 0.9883 - reward_acc: 0.9915 - val_loss: 0.8512 - val_actions_loss: 0.5576 - val_reward_loss: 0.2936 - val_actions_acc: 0.8762 - val_reward_acc: 0.8283\n",
      "Epoch 15/150\n",
      "41515/41515 [==============================] - 17s 405us/step - loss: 0.0530 - actions_loss: 0.0321 - reward_loss: 0.0209 - actions_acc: 0.9887 - reward_acc: 0.9915 - val_loss: 0.8388 - val_actions_loss: 0.5464 - val_reward_loss: 0.2924 - val_actions_acc: 0.8781 - val_reward_acc: 0.8299\n",
      "Epoch 16/150\n",
      "41515/41515 [==============================] - 20s 472us/step - loss: 0.0523 - actions_loss: 0.0310 - reward_loss: 0.0213 - actions_acc: 0.9888 - reward_acc: 0.9916 - val_loss: 0.8374 - val_actions_loss: 0.5433 - val_reward_loss: 0.2941 - val_actions_acc: 0.8791 - val_reward_acc: 0.8301\n",
      "Epoch 17/150\n",
      "41515/41515 [==============================] - 17s 408us/step - loss: 0.0509 - actions_loss: 0.0306 - reward_loss: 0.0204 - actions_acc: 0.9887 - reward_acc: 0.9916 - val_loss: 0.8373 - val_actions_loss: 0.5408 - val_reward_loss: 0.2966 - val_actions_acc: 0.8784 - val_reward_acc: 0.8298\n",
      "Epoch 18/150\n",
      "41515/41515 [==============================] - 20s 488us/step - loss: 0.0510 - actions_loss: 0.0303 - reward_loss: 0.0207 - actions_acc: 0.9887 - reward_acc: 0.9916 - val_loss: 0.8344 - val_actions_loss: 0.5407 - val_reward_loss: 0.2937 - val_actions_acc: 0.8785 - val_reward_acc: 0.8302\n",
      "Epoch 19/150\n",
      "41515/41515 [==============================] - 18s 440us/step - loss: 0.0497 - actions_loss: 0.0297 - reward_loss: 0.0201 - actions_acc: 0.9891 - reward_acc: 0.9916 - val_loss: 0.8368 - val_actions_loss: 0.5414 - val_reward_loss: 0.2953 - val_actions_acc: 0.8788 - val_reward_acc: 0.8299\n",
      "Epoch 20/150\n",
      "41515/41515 [==============================] - 20s 474us/step - loss: 0.0494 - actions_loss: 0.0296 - reward_loss: 0.0198 - actions_acc: 0.9891 - reward_acc: 0.9916 - val_loss: 0.8379 - val_actions_loss: 0.5417 - val_reward_loss: 0.2962 - val_actions_acc: 0.8791 - val_reward_acc: 0.8299\n",
      "Epoch 21/150\n",
      "41515/41515 [==============================] - 19s 463us/step - loss: 0.0496 - actions_loss: 0.0297 - reward_loss: 0.0199 - actions_acc: 0.9892 - reward_acc: 0.9916 - val_loss: 0.8393 - val_actions_loss: 0.5423 - val_reward_loss: 0.2971 - val_actions_acc: 0.8787 - val_reward_acc: 0.8297\n",
      "Epoch 22/150\n",
      "41515/41515 [==============================] - 20s 473us/step - loss: 0.0493 - actions_loss: 0.0295 - reward_loss: 0.0199 - actions_acc: 0.9894 - reward_acc: 0.9916 - val_loss: 0.8401 - val_actions_loss: 0.5428 - val_reward_loss: 0.2973 - val_actions_acc: 0.8789 - val_reward_acc: 0.8298\n",
      "Epoch 23/150\n",
      "41515/41515 [==============================] - 20s 470us/step - loss: 0.0495 - actions_loss: 0.0295 - reward_loss: 0.0200 - actions_acc: 0.9892 - reward_acc: 0.9916 - val_loss: 0.8409 - val_actions_loss: 0.5432 - val_reward_loss: 0.2977 - val_actions_acc: 0.8788 - val_reward_acc: 0.8298\n",
      "Epoch 24/150\n",
      "41515/41515 [==============================] - 19s 448us/step - loss: 0.0493 - actions_loss: 0.0295 - reward_loss: 0.0198 - actions_acc: 0.9892 - reward_acc: 0.9916 - val_loss: 0.8415 - val_actions_loss: 0.5436 - val_reward_loss: 0.2979 - val_actions_acc: 0.8787 - val_reward_acc: 0.8298\n",
      "Epoch 25/150\n",
      "41515/41515 [==============================] - 19s 462us/step - loss: 0.0494 - actions_loss: 0.0295 - reward_loss: 0.0199 - actions_acc: 0.9891 - reward_acc: 0.9916 - val_loss: 0.8419 - val_actions_loss: 0.5438 - val_reward_loss: 0.2981 - val_actions_acc: 0.8787 - val_reward_acc: 0.8301\n",
      "Epoch 26/150\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "41515/41515 [==============================] - 20s 489us/step - loss: 0.0493 - actions_loss: 0.0294 - reward_loss: 0.0199 - actions_acc: 0.9892 - reward_acc: 0.9916 - val_loss: 0.8423 - val_actions_loss: 0.5440 - val_reward_loss: 0.2983 - val_actions_acc: 0.8785 - val_reward_acc: 0.8302\n",
      "Epoch 27/150\n",
      "41515/41515 [==============================] - 20s 486us/step - loss: 0.0494 - actions_loss: 0.0295 - reward_loss: 0.0199 - actions_acc: 0.9891 - reward_acc: 0.9916 - val_loss: 0.8427 - val_actions_loss: 0.5442 - val_reward_loss: 0.2985 - val_actions_acc: 0.8784 - val_reward_acc: 0.8289\n",
      "Epoch 28/150\n",
      "41515/41515 [==============================] - 20s 479us/step - loss: 0.0493 - actions_loss: 0.0295 - reward_loss: 0.0198 - actions_acc: 0.9892 - reward_acc: 0.9916 - val_loss: 0.8430 - val_actions_loss: 0.5444 - val_reward_loss: 0.2986 - val_actions_acc: 0.8784 - val_reward_acc: 0.8289\n",
      "Epoch 29/150\n",
      "41515/41515 [==============================] - 18s 442us/step - loss: 0.0493 - actions_loss: 0.0295 - reward_loss: 0.0199 - actions_acc: 0.9892 - reward_acc: 0.9916 - val_loss: 0.8432 - val_actions_loss: 0.5446 - val_reward_loss: 0.2986 - val_actions_acc: 0.8784 - val_reward_acc: 0.8289\n",
      "Epoch 00029: early stopping\n",
      "################### ITERATION 2 ###################\n",
      "Generate dataset\n",
      "Creating child processes\n",
      "Setting start episode to 0\n",
      "  0%|                                                   | 0/150 [00:00<?, ?it/s]Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "Import error! You will not be able to render --> Cannot connect to \"None\"\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6\n",
      "  return f(*args, **kwds)\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n",
      "/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "Using TensorFlow backend.\n",
      "2018-06-17 08:45:55.419446: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419461: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419445: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419447: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419464: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419468: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419470: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419658: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419748: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419749: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419775: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:45:55.419820: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "2018-06-17 08:46:06.079981: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-20:\n",
      "2018-06-17 08:46:06.080370: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "2018-06-17 08:46:06.080650: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-19:\n",
      "Process SpawnProcess-14:\n",
      "2018-06-17 08:46:06.087161: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-18:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2018-06-17 08:46:06.418109: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-17:\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "2018-06-17 08:46:06.435228: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "2018-06-17 08:46:06.435384: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-15:\n",
      "Process SpawnProcess-16:\n",
      "2018-06-17 08:46:06.435543: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "2018-06-17 08:46:06.435679: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-23:\n",
      "Process SpawnProcess-13:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "2018-06-17 08:46:06.436836: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "2018-06-17 08:46:06.436998: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "Process SpawnProcess-22:\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "Process SpawnProcess-24:\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "2018-06-17 08:46:06.438062: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 12786073600\n",
      "Process SpawnProcess-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n",
      "Traceback (most recent call last):\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 347, in runner\n",
      "    init_tensorflow()\n",
      "  File \"/gpfs/hpchome/anton95/playground/rl_agent/MCTS.py\", line 327, in init_tensorflow\n",
      "    K.set_session(tf.Session(config=config))\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1482, in __init__\n",
      "    super(Session, self).__init__(target, graph, config=config)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 622, in __init__\n",
      "    self._session = tf_session.TF_NewDeprecatedSession(opts, status)\n",
      "  File \"/gpfs/hpchome/anton95/.conda/envs/pommerman/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 473, in __exit__\n",
      "    c_api.TF_GetCode(self.status.status))\n",
      "tensorflow.python.framework.errors_impl.InternalError: Failed to create session.\n"
     ]
    }
   ],
   "source": [
    "! python MCTS.py MCTS --load_model=\"./supervised_learning/model/go_3res_block/model.h4\" --logdir=\"go_3res_block_15\" --num_rollouts=150 --num_iters=10 --num_runners=12 --batch_size=2048 --num_epochs=150 --validation_split=0.15 --mcts_iters=15 --mcts_c_puct=1 --discount=0.99"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
